### PR TITLE
project refactored to use operator-sdk from operator framework

### PR DESCRIPTION
**Pull request by enekofb**
Refactored to use https://github.com/operator-framework
That brings

- easier development
- easier deployment
- improved watching loop

### CODE REVIEW

**Comment by linki** [comment]
@enekofb Awesome, thanks! I'll probably clean it up little and I need some time to make myself familiar with the operator framework.

**Comment by linki** [comment]
These are my changes on top of your's: https://github.com/linki/cloudformation-operator/pull/15/commits/79c62a73dd93ea8494a58deb3bbb49e68c0825f1

**Comment by enekofb** [comment]
Great change not having the loop. I have verified the changes and updated README with some details about how to test locally. Feel free to merge it if you think that is good enough.

**Comment by linki** [comment]
@enekofb Thank you. I just remembered that we can also use env vars instead of flags to configure the operator when using `operator-sdk up local`. This avoids changing the `init()` function. I commited the code. If you think this is good I'm going to merge it 😃

**Comment by enekofb** [comment]
Awesome! thumbs up from my side :)

**Comment by linki** [comment]
Cool, thanks @enekofb

**Comment by linki** [comment]
Released as `v0.2.0` (https://github.com/linki/cloudformation-operator/releases/tag/v0.2.0)

**Pull request merged**
